using System;
using System.Buffers.Binary;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Xml.Linq;
using Avalonia.Platform;
using FFXProjectEditor.Tests.Infrastructure;
using Xunit;

namespace FFXProjectEditor.Tests.Release;

// ── Approved Studio artwork and compiled resource wiring ──
// Provenance: official Spira_Reforge_Studio_Editor_Handoff_2026-08-26.zip, production/studio.
// The art is copied unchanged from the Launcher lane, not newly generated by the Editor lane.
// MAINT: source/resource hashes do not prove Windows associated-icon rendering or GUI acceptance.
public sealed class StudioBrandingContractTests
{
    private const string Asset = "Assets/SpiraReforgeStudio.ico";
    private const string ExpectedSha256 = "CB1EA30101F52EBEF7D46529446158892C2AD8B45A666AD9ADB522CA705D39FE";

    [Fact]
    public void Project_UsesTheSameLocalOfficialIcon_ForExecutableContentAndAvaloniaResource()
    {
        var project = XDocument.Load(ProductPath("FFXProjectEditor.csproj"));
        Assert.Equal(Asset, Normalize(Assert.Single(project.Descendants("ApplicationIcon")).Value));
        foreach (string itemType in new[] { "Content", "AvaloniaResource" })
        {
            var icon = Assert.Single(project.Descendants(itemType)
                .Where(item => Normalize((string?)item.Attribute("Include") ?? string.Empty) == Asset));
            Assert.Null(icon.Attribute("Condition")); // Both desktop backends must receive it.
        }
        Assert.DoesNotContain(project.Descendants("Content"), item =>
            Normalize((string?)item.Attribute("Include") ?? string.Empty) == "Assets/FFXProjectEditor_Logo.ico");
    }

    [Fact]
    public void MainWindow_UsesTheOfficialResource_WithoutRenamingTheExistingProduct()
    {
        var window = XDocument.Load(ProductPath("Modules", "Main", "Main_Window.axaml")).Root!;
        Assert.Equal("/" + Asset, (string?)window.Attribute("Icon"));
        Assert.Equal("Spira Reforge Studio", (string?)window.Attribute("Title"));
        XNamespace xaml = "http://schemas.microsoft.com/winfx/2006/xaml";
        Assert.Equal("FFXProjectEditor.Main_Window", (string?)window.Attribute(xaml + "Class"));
        Assert.Equal("FFXProjectEditor", typeof(App).Assembly.GetName().Name);
    }

    [Fact]
    public void LocalIcon_HasTheApprovedHash_AndSevenPngDirectoryEntries()
    {
        string path = ProductPath("Assets", "SpiraReforgeStudio.ico");
        Assert.True(File.Exists(path), "The official Studio icon must be local to the Editor.");
        byte[] bytes = File.ReadAllBytes(path);
        Assert.Equal(ExpectedSha256, Convert.ToHexString(SHA256.HashData(bytes)));
        Assert.Equal(0, BinaryPrimitives.ReadUInt16LittleEndian(bytes.AsSpan(0, 2)));
        Assert.Equal(1, BinaryPrimitives.ReadUInt16LittleEndian(bytes.AsSpan(2, 2)));
        Assert.Equal(7, BinaryPrimitives.ReadUInt16LittleEndian(bytes.AsSpan(4, 2)));
        int[] sizes = { 16, 20, 24, 32, 48, 64, 256 };
        byte[] pngSignature = { 137, 80, 78, 71, 13, 10, 26, 10 };
        for (int index = 0; index < sizes.Length; index++)
        {
            int entry = 6 + index * 16;
            Assert.Equal(sizes[index], bytes[entry] == 0 ? 256 : bytes[entry]);
            Assert.Equal(sizes[index], bytes[entry + 1] == 0 ? 256 : bytes[entry + 1]);
            Assert.Equal(1, BinaryPrimitives.ReadUInt16LittleEndian(bytes.AsSpan(entry + 4, 2)));
            Assert.Equal(32, BinaryPrimitives.ReadUInt16LittleEndian(bytes.AsSpan(entry + 6, 2)));
            int length = checked((int)BinaryPrimitives.ReadUInt32LittleEndian(bytes.AsSpan(entry + 8, 4)));
            int offset = checked((int)BinaryPrimitives.ReadUInt32LittleEndian(bytes.AsSpan(entry + 12, 4)));
            Assert.InRange(length, 8, bytes.Length);
            Assert.InRange(offset, 6 + sizes.Length * 16, bytes.Length - length);
            Assert.Equal(pngSignature, bytes.AsSpan(offset, 8).ToArray());
        }
        // Full PNG CRC/IDAT/filter decoding is separately verified by the handoff validator.
    }

    [Fact]
    public void CompiledAvaloniaResource_ContainsTheExactOfficialIconBytes()
    {
        // Public loader API from the pinned Avalonia11.2.3; independent instance avoids global
        // application/renderer initialization and reads the actual compiled resource table.
        StandardAssetLoader.RegisterResUriParsers();
        var loader = new StandardAssetLoader(typeof(App).Assembly);
        using var icon = loader.Open(new Uri("avares://FFXProjectEditor/" + Asset));
        Assert.Equal(ExpectedSha256, Convert.ToHexString(SHA256.HashData(icon)));
    }

    private static string Normalize(string path) => path.Replace('\\', '/');

    private static string ProductPath(params string[] parts) =>
        Path.Combine(new[] { TestDataPaths.RepoRoot, "FFXProjectEditor" }.Concat(parts).ToArray());
}
