using System;
using System.Collections.Generic;

namespace FFXProjectEditor.Modules.MagicDllEditor
{
    /// <summary>
    /// Catálogo embutido de nomes de efeitos (fonte noclip.website, 2026-07-31).
    /// Fallback offline do JSON em work/noclip_reference/ (gitignored) — garante que o
    /// editor resolva nomes ("Power Break", "Cheer"...) mesmo em produção sem a pasta work.
    /// Gerado por work/ppp_c2/_onda8_gen_names.py em 2026-08-02 (471 nomes).
    /// </summary>
    internal static partial class MagicEffectNameCatalog
    {
        private static readonly IReadOnlyDictionary<string, string> EmbeddedNames =
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
            { "3", "Cheer" },
            { "4", "Focus" },
            { "5", "Reflex" },
            { "6", "Aim" },
            { "7", "Luck" },
            { "8", "Jinx" },
            { "9", "Lancet" },
            { "10", "Haste" },
            { "14", "Slow" },
            { "18", "Spare Change" },
            { "20", "Scan" },
            { "21", "Power Break" },
            { "22", "Sleep Attack" },
            { "24", "Silence Attack" },
            { "26", "Dark Attack" },
            { "28", "Triple Foul" },
            { "30", "Zombie Attack" },
            { "32", "Mana Distiller" },
            { "34", "Sleep Buster" },
            { "36", "Silence Buster" },
            { "38", "Dark Buster" },
            { "40", "Power Distiller" },
            { "42", "Anima Summon?, Multiple Headers" },
            { "45", "Water Ripples?" },
            { "46", "Speed Distiller" },
            { "48", "Move Distiller (Unused)" },
            { "50", "Ability Distiller" },
            { "52", "Threaten Find Funcs" },
            { "53", "unk_35" },
            { "54", "Entrust" },
            { "55", "Bribe" },
            { "64", "Threaten Alt :(:(" },
            { "65", "Provoke Alt" },
            { "69", "Sonic Boom" },
            { "70", "Ixion Summon" },
            { "71", "Aerospark" },
            { "72", "Breath (Demonolith)" },
            { "73", "Delay Buster" },
            { "74", "Blizzard" },
            { "76", "Fire" },
            { "78", "Thunder" },
            { "80", "Water" },
            { "82", "Fira" },
            { "84", "Blizzara" },
            { "86", "Thundara" },
            { "88", "Watera" },
            { "90", "Firaga" },
            { "92", "Blizzaga" },
            { "94", "Thundaga" },
            { "96", "Waterga" },
            { "98", "Death" },
            { "100", "Bio" },
            { "102", "Demi" },
            { "104", "Flare" },
            { "106", "Ultima" },
            { "108", "Cure" },
            { "110", "Cura" },
            { "112", "Curaga" },
            { "114", "Life" },
            { "116", "Full Life" },
            { "119", "Summon ?" },
            { "120", "Esuna" },
            { "122", "Regen" },
            { "124", "Dispel" },
            { "126", "Shell" },
            { "128", "Protect" },
            { "130", "Reflect" },
            { "132", "Drain" },
            { "134", "Osmose" },
            { "136", "Nulfrost" },
            { "138", "Nulblaze" },
            { "140", "Nulshock" },
            { "142", "Nultide" },
            { "144", "Auto Life" },
            { "146", "Holy" },
            { "148", "Valefor Summon?   Texture Issues" },
            { "149", "Sonic Wings" },
            { "150", "Energy Ray" },
            { "151", "Energy Blast" },
            { "152", "Anima Summon?" },
            { "153", "Pain ???" },
            { "154", "Oblivion" },
            { "155", "Thor's Hammer" },
            { "157", "Delay Attack" },
            { "159", "unk_9f" },
            { "160", "Ixion Death" },
            { "161", "Ifrit Death" },
            { "162", "Shiva Summon" },
            { "163", "Heavenly Strike" },
            { "164", "Thor's Hammer Again" },
            { "165", "Diamond Dust" },
            { "166", "unk_a6" },
            { "167", "Shiva Death" },
            { "168", "Issue With Clut Format?" },
            { "169", "Impulse" },
            { "170", "Mega Flare, Lots Of Parts" },
            { "171", "Breath (Vouivre)" },
            { "172", "Ice Breath" },
            { "173", "Lightning Breath" },
            { "174", "Fire Breath" },
            { "175", "White Wind" },
            { "176", "Black Stare" },
            { "177", "Shockwave" },
            { "178", "Seed Canmon" },
            { "179", "Seed Burst" },
            { "180", "Water Spurt (Sahagin)" },
            { "182", "Sonic Boom" },
            { "183", "Land Worm Swallow" },
            { "184", "Land Worm Regurgitate" },
            { "185", "Earthquake" },
            { "186", "Blast Punch" },
            { "187", "Rifle" },
            { "188", "Doom" },
            { "189", "Sonic Wave" },
            { "190", "Maelstrom" },
            { "191", "Salvo" },
            { "197", "unk_c5" },
            { "199", "Gnaw?" },
            { "200", "Blades" },
            { "201", "Heave" },
            { "202", "Tail" },
            { "203", "Meteor Issues" },
            { "205", "unk_cd" },
            { "206", "unk_ce" },
            { "207", "Electrocute" },
            { "208", "unk_d0" },
            { "217", "Ether" },
            { "219", "Turbo Ether" },
            { "221", "Elixir" },
            { "229", "Antidote" },
            { "231", "Soft" },
            { "233", "Eye Drops" },
            { "235", "Echo Screen" },
            { "237", "Holy Water" },
            { "241", "Grenade" },
            { "243", "Nautilus Charge" },
            { "244", "Geneaux Appears" },
            { "245", "Toxic Cloud" },
            { "246", "Venom" },
            { "247", "Staccato" },
            { "248", "Geneaux Transform" },
            { "249", "Geneaux Death" },
            { "250", "Thwack" },
            { "251", "Thwack 2" },
            { "252", "[Death]" },
            { "253", "[Death 2]???" },
            { "255", "[Death]" },
            { "256", "Mimic 1" },
            { "257", "Geosgano Death" },
            { "259", "Out Of Breath Range" },
            { "260", "Spines" },
            { "261", "Poison Breath" },
            { "262", "Geosgano Swallow" },
            { "263", "Geosgano Regurgitate" },
            { "264", "Photon Spray" },
            { "265", "Eraser" },
            { "266", "Blender" },
            { "267", "[Death]" },
            { "269", "Gatling Gun" },
            { "270", "Mana Beam" },
            { "271", "Karma" },
            { "272", "Leaping Swing" },
            { "273", "Double Reaper" },
            { "274", "Stone Gaze" },
            { "275", "Voodoo" },
            { "276", "Sonic Tail" },
            { "277", "Adamantoise Breath" },
            { "278", "Earthquake" },
            { "279", "Valefor Death?" },
            { "280", "Emblem Of Fate" },
            { "281", "Core Energy Chain Target Issue" },
            { "282", "Shimmering Rain" },
            { "283", "Nova" },
            { "284", "Blitzball Rush" },
            { "285", "Doze Ball" },
            { "286", "Blind Ball" },
            { "287", "Mute Ball" },
            { "288", "Crane" },
            { "289", "Aqua Shooter" },
            { "290", "Depth Charges" },
            { "291", "unk_123" },
            { "292", "Cage" },
            { "293", "Landing" },
            { "294", "[Death] ?" },
            { "295", "Venom" },
            { "296", "Stone Gaze" },
            { "297", "[Death]?" },
            { "298", "Clut Format Issue" },
            { "299", "Ochu Dance" },
            { "300", "Cannon (Single)" },
            { "301", "Cannon (All)" },
            { "302", "Anima Death" },
            { "303", "[Death]?" },
            { "304", "Summon" },
            { "305", "Meteor Strike" },
            { "307", "Hellfire" },
            { "308", "unk_134" },
            { "309", "unk_135" },
            { "310", "Seymour Dismisses" },
            { "311", "Self Destruct" },
            { "314", "Mana Breath" },
            { "315", "Photon Spray" },
            { "316", "Something Dying" },
            { "317", "Cross Cleave" },
            { "318", "Machina Death" },
            { "319", "Magic Break" },
            { "320", "Armor Break" },
            { "321", "Mental Break" },
            { "323", "Small Smoke Puff" },
            { "324", "Bahamut Death" },
            { "325", "[Something Death]" },
            { "330", "unk_14a" },
            { "332", "Thunder" },
            { "333", "Water" },
            { "334", "Berserk" },
            { "335", "Sleep" },
            { "336", "Blind" },
            { "337", "Confuse" },
            { "338", "Curse" },
            { "339", "Silence" },
            { "340", "[Death]" },
            { "341", "Gagazet Prominence Seymour Effect" },
            { "342", "Elemental Shift" },
            { "343", "[Death]" },
            { "344", "Spectral Keeper Death" },
            { "346", "Magic Circle Attack" },
            { "347", "Drain Fury" },
            { "348", "Metamorphosis" },
            { "349", "Hellbiter" },
            { "350", "Metamorphosis 2" },
            { "351", "Mega Death" },
            { "352", "Mind Blast" },
            { "353", "??" },
            { "354", "Bulldoze" },
            { "355", "Guided Missiles" },
            { "356", "1000 Needles" },
            { "357", "10000 Needles (Not Seeing Any Needles Yet)" },
            { "358", "Poison Mist" },
            { "359", "Body Splash" },
            { "360", "Mortar" },
            { "361", "Malboro Munch" },
            { "367", "Event Klikk Appearance Effects" },
            { "368", "Event Extractor Fight Intro Bubble Stream" },
            { "369", "unk_171" },
            { "370", "Event Sahagin Being Eaten" },
            { "371", "Event Sahagin Dive Splashes" },
            { "372", "Event Besaid Splash" },
            { "374", "Event Geosgano Platform Collapse" },
            { "375", "Geosgano Escape Corridor Entrance" },
            { "376", "Geosgano" },
            { "377", "Pollen" },
            { "378", "Break" },
            { "379", "Banish" },
            { "380", "Desperado" },
            { "381", "[Death Anim]" },
            { "382", "Megiddo Flame" },
            { "383", "Lake Macalania Ice Cracking" },
            { "384", "Aqua Breath" },
            { "385", "Photon Wings" },
            { "386", "Requiem" },
            { "387", "Total Annihilation" },
            { "388", "unk_184" },
            { "389", "Macalania Spring, Spherimorph Spawn" },
            { "390", "Spiral Cut" },
            { "391", "Slice & Dice" },
            { "392", "Energy Rain" },
            { "393", "Blitz Ace" },
            { "394", "Shooting Star" },
            { "395", "Dragon Fang" },
            { "396", "Banishing Blade" },
            { "397", "Tornado" },
            { "398", "unk_18e" },
            { "399", "Panacea" },
            { "400", "Hot Spurs" },
            { "401", "Eccentrick" },
            { "402", "Nulall" },
            { "404", "Freedom" },
            { "405", "Quartet Of 9" },
            { "411", "unk_19b" },
            { "412", "Thundara Fury" },
            { "413", "Blizzara Fury" },
            { "414", "Watera Fury" },
            { "415", "Fire Breath" },
            { "416", "Bad Breath" },
            { "417", "Stone Breath" },
            { "419", "Self Destruct" },
            { "420", "Seed Cannon" },
            { "421", "Aqua Breath" },
            { "424", "Dark Matter" },
            { "425", "Firaga Fury" },
            { "426", "Vitality" },
            { "427", "Mana" },
            { "428", "Miracle Drink Squares" },
            { "429", "Death" },
            { "430", "Yojimbo Summon?" },
            { "431", "Kozuka" },
            { "432", "Wakizashi Trail Issue" },
            { "434", "Zanmato" },
            { "435", "unk_1b3" },
            { "436", "[Death]" },
            { "437", "[Death]" },
            { "438", "[Death]" },
            { "439", "Thundaga Fury (~Same)" },
            { "440", "Blizzaga Fury (~Same)" },
            { "441", "Waterga Fury (~Same)" },
            { "442", "Demi Fury" },
            { "443", "Death Fury" },
            { "444", "Flare Fury (~Same)" },
            { "445", "Ultima Fury" },
            { "446", "Power Shot?!?!" },
            { "469", "(Sin's Fin) Gravija" },
            { "470", "Negation" },
            { "472", "Genais [Enters Shell]" },
            { "473", "Giga Graviton" },
            { "474", "(Sin's Head) Gaze" },
            { "475", "(Sin's Head) Gravija" },
            { "476", "Event Fighting Sin [Death]" },
            { "477", "Event Besaid Splashes?" },
            { "478", "Jecht Bomber" },
            { "479", "Event Baaj Door Explosion" },
            { "480", "Event Baaj Spark" },
            { "481", "event salvage deck sin attack" },
            { "482", "Jecht Beam" },
            { "483", "event oblitzerator appearance dust?" },
            { "484", "Event Salvage Ship (Bright Light?)" },
            { "485", "Geneaux [Tentacles Absorb]" },
            { "486", "Event Oasis Splash" },
            { "487", "Event Besaid Swimming Trail?" },
            { "488", "Event Luca Water Lines" },
            { "489", "Event Ss Liki Battle Start" },
            { "490", "Event Ss Liki Splash" },
            { "491", "Osmose Fury" },
            { "492", "Bio Fury" },
            { "493", "unk_1ed" },
            { "494", "Blizzard Fury" },
            { "495", "Thunder Fury" },
            { "496", "Event Kilika Port Smoke" },
            { "497", "Event Bevelle Tower Of Light Yuna Transform" },
            { "498", "Event Bevelle Fayth Light" },
            { "499", "event Luca dock 2 machina activate" },
            { "500", "Water Fury" },
            { "505", "Event Blitzball blitzoff spinning" },
            { "507", "unk_1fb" },
            { "508", "Jump" },
            { "510", "Thrust Kick" },
            { "511", "Magus Sister Summoning (Textures Need Separate Loading)" },
            { "512", "Razzia" },
            { "513", "Camisade" },
            { "514", "Passado" },
            { "515", "Delta Attack" },
            { "516", "[Death]" },
            { "519", "unk_207" },
            { "521", "Bingo!" },
            { "522", "Wrong!" },
            { "523", "Event Home Outside" },
            { "525", "Megaton" },
            { "526", "Slime (Long Lasting Particle)" },
            { "527", "Event Maca Woods Central Celestial Sphere Interaction?" },
            { "528", "Neslug Broken Shell" },
            { "529", "[Death]" },
            { "530", "Blaster" },
            { "531", "Hyper Blaster" },
            { "533", "Summon Anima (There's A Second Texture Header)" },
            { "534", "Fire Breath" },
            { "535", "Aqua Breath" },
            { "536", "Event Home Env Controls Pyreflies" },
            { "537", "Al Bhed Home Pyreflies?" },
            { "539", "Event Via Purifico Evrae Pyrefly Stream" },
            { "540", "Event Stbv0100 Huge Pyrefly Swarm" },
            { "543", "Fire Shot" },
            { "544", "Ice Shot" },
            { "545", "Water Shot" },
            { "546", "Thunder Shot?" },
            { "551", "Gravija" },
            { "553", "Event Zanarkand Boss Appearance" },
            { "554", "Negation (Again...)" },
            { "555", "Attack Reels" },
            { "556", "Havoc Shot" },
            { "557", "Time Shot" },
            { "558", "Break Shot" },
            { "559", "Aurochs Shot" },
            { "561", "Event Lchb0800 Sparkle" },
            { "562", "Genais [Death]" },
            { "563", "Hellfire Again" },
            { "564", "unk_234" },
            { "565", "Reels" },
            { "568", "Ifrit Summon (Battle?)" },
            { "570", "Ixion Summon (Battle?)" },
            { "571", "Mighty Guard" },
            { "572", "Hyper Mighty Guard (Similar To 23b?)" },
            { "573", "Triumphant Grasp (Bfa)" },
            { "577", "Ultimate Jecht Shot Texture Issues" },
            { "578", "Power Wave (Bahamut Yu Yevon)" },
            { "581", "Event Sins0700 (Yu Yevon Battle?)" },
            { "582", "Command 254 (Yu Yevon)" },
            { "585", "Draws Sword (Bfa)" },
            { "586", "Shiva Summon (Yu Yevon)" },
            { "587", "Bahamut Summon (Yu Yevon) Palette Issue" },
            { "588", "Yojimbo Summon (Yu Yevon)" },
            { "589", "Maguc Sisters Summon (Yu Yevon)" },
            { "590", "Negation" },
            { "591", "Hellbiter (Different Yunalesca Phase??)" },
            { "592", "Magic Absorbed (Sin)" },
            { "595", "Unused Valefor Summon" },
            { "596", "??? Ring Of Black Rocks With Swirl Above Them" },
            { "597", "Unused Ixion Summon" },
            { "598", "Unused Shiva Summon" },
            { "599", "Unused Bahamut Summon" },
            { "600", "Unused Yojimbo Summon" },
            { "601", "Unused Anima Summon" },
            { "602", "Unused Magus Summon" },
            { "611", "Find Funcs (Delta Attack)" },
            { "616", "Event Dome0600 Black Column" },
            { "617", "Event Dome0600 Death" },
            { "618", "Bad Data" },
            { "620", "Electricity Issue" },
            { "621", "Watera????" },
            { "622", "Yu Yevon Death?" },
            { "623", "Yu Yevon Death..." },
            { "624", "''" },
            { "625", "unk_271" },
            { "626", "unk_272" },
            { "627", "unk_273" },
            { "628", "unk_274" },
            { "629", "Yu Yevon Death" },
            { "630", "Possessed By Yu Yevon" },
            { "631", "''" },
            { "632", "unk_278" },
            { "633", "unk_279" },
            { "634", "unk_27a" },
            { "635", "unk_27b" },
            { "636", "unk_27c" },
            { "637", "Possessed By Yu Yevon" },
            { "638", "Event Znkd0801 Explosion/Shatter" },
            { "640", "No Textures??" },
            { "641", "Event Swin0000 Blue Wibbly Aura" },
            { "645", "Omnis Death" },
            { "649", "Power Wave (Bfa?)" },
            { "650", "Dream Powder" },
            { "652", "Silence Grenade" },
            { "653", "Smoke Bomb" },
            { "656", "Petrify Grenade" },
            { "658", "Event Sins0300 Pyreflies (Bfa Death?)" },
            { "659", "Thrashing (Genais)" },
            { "660", "Exits Shell (Genais)" },
            { "661", "Event Mcfr0100 Sparkles" },
            { "662", "Title Screen" },
            { "664", "Event Mcfr1200 Splash" },
            { "665", "Event Mcfr1200 Splash" },
            { "666", "Event Mcfr1200 Splash" },
            { "667", "Find Funcs" },
            { "668", "Find Funcs" },
            { "669", "Event Sins0600 Yu Yevon?" },
            { "670", "Game Over" },
            { "671", "Game Over 2" },
            { "672", "[ Death Anim ]" },
            { "673", "Tanker Explosion" },
            { "675", "Black Ice" },
            { "676", "Thunderbolt" },
            { "677", "Waterfall" },
            { "678", "Abaddon Flame" },
            { "680", "Ice Gem" },
            { "682", "Lightning Gem" },
            { "684", "Water Gem" },
            { "686", "Farplane Wind" },
            { "688", "Event Zanarkand Overpass Explosion" },
            { "689", "Event Zanarkand Overpass Explosion" },
            { "690", "Candle Of Life (Same As Death?)" },
            { "699", "Full Break" },
            { "706", "Judgement Day" },
            { "708", "Penance Death" },
            };
    }
}
