<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>BattleTrackerProbe</AssemblyName>
    <RootNamespace>BattleTrackerProbe</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Binarysharp.MSharp">
      <HintPath>..\..\ExternalLibs\MemorySharp64\Binarysharp.MSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
