// <auto-generated> DO NOT EDIT BY HAND.
// Byte-grounded compiled table of FFX PC/Aeon growth + stats decoded from ply_save.bin + ply_rom.bin.
// Source region: new_uspc (the region PlayerGrowthEditor loads). REGION-SPECIFIC, NOT locale-invariant:
//   unlike sum_grow.bin, the ply_save/ply_rom data sections differ across jppc/uspc/inpc.
// Shape: 0x14 header + 20 x save 0x94 + 20 x rom 0x2C. Structure RT0-proved by --player-rt0
//   (PlayerKernel_File.ReadSave/ReadRom no-edit Read->Write byte-identical).
// Regenerate: pwsh tools/ffxdataparser_bridge/build_player_growth_index.ps1 -EmitCSharp <thisFile>
// Only RAW decoded fields are embedded; character labels resolve at RUNTIME via Character_Enum.
// Read-only Atlas data - never a writer, never work/-dependent. Lane: Jarvis-TIDUS.
namespace FFXProjectEditor.FfxLib.SpiraDataAtlas
{
    // ply_save: Base* + current snapshot (kernel defaults). ply_rom: AP-requirement curve (ApReq*) +
    // per-stat auto-growth coefficients (*CoefA/B). PC slots carry ~zero stat coefficients (PCs grow via the
    // Sphere Grid); the populated stat coefficients are Aeon slots. The ApReq curve is the PC growth knob.
    internal readonly record struct PlayerGrowthRow(
        int Index,
        int BaseHp, int BaseMp, byte BaseStr, byte BaseDef, byte BaseMag, byte BaseMdf, byte BaseAgi, byte BaseLck, byte BaseEva, byte BaseAcc,
        int CurAp, int CurHp, int CurMp, int MaxHp, int MaxMp, byte OdMode, byte SphAvail, byte SphUsed,
        byte Genre, byte ApReqA, byte ApReqB, byte ApReqC, int ApReqMax,
        byte HpA, byte HpB, byte MpA, byte MpB, byte StrA, byte StrB, byte DefA, byte DefB, byte MagA, byte MagB,
        byte MdfA, byte MdfB, byte AgiA, byte AgiB, byte EvaA, byte EvaB, byte AccA, byte AccB, ushort Tail);

    internal static class PlayerGrowthData
    {
        public const string SourceRegion = "new_uspc";
        public const int SaveEntryLength = 0x94;
        public const int RomEntryLength = 0x2C;
        public const int EntryCount = 20;

        public static readonly PlayerGrowthRow[] Rows =
        {
            new PlayerGrowthRow(0, 520, 12, 15, 10, 5, 5, 10, 18, 10, 10, 0, 520, 12, 520, 12, 2, 0, 0, 1, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(1, 475, 84, 5, 5, 20, 20, 10, 17, 30, 3, 0, 475, 84, 475, 84, 2, 0, 2, 2, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(2, 1030, 33, 20, 15, 5, 5, 5, 17, 5, 3, 0, 1030, 33, 1030, 33, 2, 0, 12, 1, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(3, 644, 78, 16, 15, 17, 5, 6, 18, 5, 5, 0, 644, 78, 644, 78, 2, 0, 6, 1, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(4, 618, 10, 14, 10, 10, 5, 7, 19, 5, 25, 0, 618, 10, 618, 10, 2, 0, 2, 1, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(5, 380, 92, 5, 8, 20, 30, 5, 17, 40, 3, 0, 380, 92, 380, 92, 2, 0, 2, 2, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(6, 360, 85, 10, 8, 10, 8, 16, 18, 5, 5, 0, 360, 85, 360, 85, 2, 0, 25, 2, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(7, 1200, 999, 20, 25, 35, 100, 20, 18, 10, 10, 0, 1200, 999, 1000, 1000, 2, 0, 0, 1, 2, 0, 5, 22000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0005),
            new PlayerGrowthRow(8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 6, 20, 2, 4, 7, 6, 5, 5, 70, 10, 30, 10, 20, 5, 24, 5, 20, 20, 0x0800),
            new PlayerGrowthRow(9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 5, 70, 2, 3, 7, 8, 5, 17, 33, 9, 34, 9, 20, 4, 70, 3, 20, 20, 0x0C00),
            new PlayerGrowthRow(10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 6, 55, 2, 5, 7, 10, 5, 10, 38, 9, 30, 13, 20, 3, 47, 3, 20, 25, 0x1400),
            new PlayerGrowthRow(11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 6, 40, 2, 7, 8, 12, 7, 4, 28, 10, 25, 10, 23, 10, 44, 10, 20, 20, 0x1400),
            new PlayerGrowthRow(12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 7, 100, 3, 5, 7, 16, 6, 20, 250, 9, 12, 10, 20, 5, 20, 5, 20, 20, 0x1800),
            new PlayerGrowthRow(13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 8, 120, 4, 4, 6, 33, 5, 10, 12, 7, 30, 10, 20, 4, 20, 5, 20, 20, 0x1800),
            new PlayerGrowthRow(14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 4, 0, 0, 0, 0, 9, 18, 0, 0, 6, 24, 8, 25, 23, 6, 30, 10, 20, 4, 20, 18, 10, 30, 0x1800),
            new PlayerGrowthRow(15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 12, 0, 0, 0, 0, 10, 240, 3, 18, 6, 23, 6, 30, 60, 10, 12, 10, 20, 5, 20, 5, 20, 20, 0x1E00),
            new PlayerGrowthRow(16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 12, 0, 0, 0, 0, 8, 200, 3, 5, 7, 55, 6, 18, 40, 11, 12, 10, 20, 5, 20, 4, 20, 27, 0x1E00),
            new PlayerGrowthRow(17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99999, 9999, 99999, 9999, 19, 0, 0, 12, 0, 0, 0, 0, 5, 150, 4, 20, 7, 16, 6, 14, 40, 13, 12, 10, 20, 7, 20, 6, 20, 24, 0x1E00),
            new PlayerGrowthRow(18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 150, 10, 130, 5, 10, 5, 10, 10, 10, 30, 10, 20, 4, 20, 5, 20, 20, 0x0000),
            new PlayerGrowthRow(19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 150, 10, 130, 5, 10, 5, 10, 10, 10, 30, 10, 20, 4, 20, 5, 20, 20, 0x0000),
        };
    }
}
