// <auto-generated> DO NOT EDIT BY HAND.
// Byte-grounded compiled table of FFX Aeon customization recipes decoded from sum_grow.bin.
// Source: sum_grow.bin (636 bytes; 0x14 header + 77 x 8-byte entries; Target always 0x007F = Aeon;
//   jppc == inpc byte-identical). Structure RT0-proved by --customization-rt0 (Customization_File.ReadAeon).
// Regenerate: pwsh tools/ffxdataparser_bridge/build_sum_grow_aeon_fine_index.ps1 -EmitCSharp <thisFile>
// Only the RAW decoded fields are embedded; result/item NAMES are resolved at RUNTIME via the editor's own
// Customization_File.AeonCustomizationEntry + dictionaries, keeping a single source of truth for naming.
// Read-only Atlas data - never a writer, never work/-dependent.
namespace FFXProjectEditor.FfxLib.SpiraDataAtlas
{
    internal readonly record struct SumGrowAeonRecipeRow(int Index, ushort Target, ushort Result, ushort Item, byte Primary, byte Secondary);

    internal static class SumGrowAeonRecipeData
    {
        public const int SourceFileLength = 636;
        public const ushort AeonTarget = 0x007F;

        public static readonly SumGrowAeonRecipeRow[] Rows =
        {
            new SumGrowAeonRecipeRow(0, 0x007F, 0x300A, 0x2028, 6, 0),
            new SumGrowAeonRecipeRow(1, 0x007F, 0x3009, 0x2027, 3, 0),
            new SumGrowAeonRecipeRow(2, 0x007F, 0x3008, 0x2025, 3, 0),
            new SumGrowAeonRecipeRow(3, 0x007F, 0x300E, 0x2028, 12, 0),
            new SumGrowAeonRecipeRow(4, 0x007F, 0x300D, 0x2027, 10, 0),
            new SumGrowAeonRecipeRow(5, 0x007F, 0x300C, 0x2025, 10, 0),
            new SumGrowAeonRecipeRow(6, 0x007F, 0x300B, 0x200E, 99, 0),
            new SumGrowAeonRecipeRow(7, 0x007F, 0x300F, 0x204D, 4, 0),
            new SumGrowAeonRecipeRow(8, 0x007F, 0x3006, 0x202E, 20, 0),
            new SumGrowAeonRecipeRow(9, 0x007F, 0x3007, 0x202F, 30, 0),
            new SumGrowAeonRecipeRow(10, 0x007F, 0x305A, 0x2046, 20, 0),
            new SumGrowAeonRecipeRow(11, 0x007F, 0x305B, 0x2047, 20, 0),
            new SumGrowAeonRecipeRow(12, 0x007F, 0x305C, 0x2048, 20, 0),
            new SumGrowAeonRecipeRow(13, 0x007F, 0x305D, 0x2049, 20, 0),
            new SumGrowAeonRecipeRow(14, 0x007F, 0x3010, 0x203D, 8, 0),
            new SumGrowAeonRecipeRow(15, 0x007F, 0x3011, 0x203C, 4, 0),
            new SumGrowAeonRecipeRow(16, 0x007F, 0x3012, 0x2052, 2, 0),
            new SumGrowAeonRecipeRow(17, 0x007F, 0x3013, 0x2068, 4, 0),
            new SumGrowAeonRecipeRow(18, 0x007F, 0x3059, 0x2035, 2, 0),
            new SumGrowAeonRecipeRow(19, 0x007F, 0x3019, 0x2015, 5, 0),
            new SumGrowAeonRecipeRow(20, 0x007F, 0x301A, 0x2046, 5, 0),
            new SumGrowAeonRecipeRow(21, 0x007F, 0x301B, 0x2048, 5, 0),
            new SumGrowAeonRecipeRow(22, 0x007F, 0x301C, 0x2047, 10, 0),
            new SumGrowAeonRecipeRow(23, 0x007F, 0x301D, 0x2048, 10, 0),
            new SumGrowAeonRecipeRow(24, 0x007F, 0x301E, 0x204A, 2, 0),
            new SumGrowAeonRecipeRow(25, 0x007F, 0x301F, 0x204A, 2, 0),
            new SumGrowAeonRecipeRow(26, 0x007F, 0x3020, 0x203E, 20, 0),
            new SumGrowAeonRecipeRow(27, 0x007F, 0x3029, 0x2045, 5, 0),
            new SumGrowAeonRecipeRow(28, 0x007F, 0x302B, 0x2001, 99, 0),
            new SumGrowAeonRecipeRow(29, 0x007F, 0x302C, 0x2002, 30, 0),
            new SumGrowAeonRecipeRow(30, 0x007F, 0x302D, 0x2003, 60, 0),
            new SumGrowAeonRecipeRow(31, 0x007F, 0x302F, 0x201A, 2, 0),
            new SumGrowAeonRecipeRow(32, 0x007F, 0x3030, 0x201D, 2, 0),
            new SumGrowAeonRecipeRow(33, 0x007F, 0x3031, 0x2020, 2, 0),
            new SumGrowAeonRecipeRow(34, 0x007F, 0x302E, 0x2017, 2, 0),
            new SumGrowAeonRecipeRow(35, 0x007F, 0x3032, 0x2049, 10, 0),
            new SumGrowAeonRecipeRow(36, 0x007F, 0x3034, 0x2008, 8, 0),
            new SumGrowAeonRecipeRow(37, 0x007F, 0x3035, 0x2009, 1, 0),
            new SumGrowAeonRecipeRow(38, 0x007F, 0x3036, 0x2036, 10, 0),
            new SumGrowAeonRecipeRow(39, 0x007F, 0x3037, 0x2037, 16, 0),
            new SumGrowAeonRecipeRow(40, 0x007F, 0x3038, 0x202E, 4, 0),
            new SumGrowAeonRecipeRow(41, 0x007F, 0x3039, 0x202F, 8, 0),
            new SumGrowAeonRecipeRow(42, 0x007F, 0x303A, 0x2038, 4, 0),
            new SumGrowAeonRecipeRow(43, 0x007F, 0x303B, 0x2039, 6, 0),
            new SumGrowAeonRecipeRow(44, 0x007F, 0x303C, 0x203A, 3, 0),
            new SumGrowAeonRecipeRow(45, 0x007F, 0x303D, 0x203F, 3, 0),
            new SumGrowAeonRecipeRow(46, 0x007F, 0x303E, 0x203B, 60, 0),
            new SumGrowAeonRecipeRow(47, 0x007F, 0x303F, 0x202B, 60, 0),
            new SumGrowAeonRecipeRow(48, 0x007F, 0x3042, 0x201A, 1, 0),
            new SumGrowAeonRecipeRow(49, 0x007F, 0x3043, 0x201D, 1, 0),
            new SumGrowAeonRecipeRow(50, 0x007F, 0x3044, 0x2020, 1, 0),
            new SumGrowAeonRecipeRow(51, 0x007F, 0x3041, 0x2017, 1, 0),
            new SumGrowAeonRecipeRow(52, 0x007F, 0x3045, 0x201B, 2, 0),
            new SumGrowAeonRecipeRow(53, 0x007F, 0x3047, 0x201E, 2, 0),
            new SumGrowAeonRecipeRow(54, 0x007F, 0x3048, 0x2021, 2, 0),
            new SumGrowAeonRecipeRow(55, 0x007F, 0x3046, 0x2018, 2, 0),
            new SumGrowAeonRecipeRow(56, 0x007F, 0x3049, 0x201C, 4, 0),
            new SumGrowAeonRecipeRow(57, 0x007F, 0x304B, 0x201F, 4, 0),
            new SumGrowAeonRecipeRow(58, 0x007F, 0x304C, 0x2022, 4, 0),
            new SumGrowAeonRecipeRow(59, 0x007F, 0x304A, 0x2019, 4, 0),
            new SumGrowAeonRecipeRow(60, 0x007F, 0x304D, 0x202D, 8, 0),
            new SumGrowAeonRecipeRow(61, 0x007F, 0x304E, 0x2029, 8, 0),
            new SumGrowAeonRecipeRow(62, 0x007F, 0x304F, 0x2032, 30, 0),
            new SumGrowAeonRecipeRow(63, 0x007F, 0x3050, 0x203D, 60, 0),
            new SumGrowAeonRecipeRow(64, 0x007F, 0x3051, 0x203C, 10, 0),
            new SumGrowAeonRecipeRow(65, 0x007F, 0x3052, 0x202A, 60, 0),
            new SumGrowAeonRecipeRow(66, 0x007F, 0x3053, 0x202C, 99, 0),
            new SumGrowAeonRecipeRow(67, 0x007F, 0x0000, 0x2046, 100, 1),
            new SumGrowAeonRecipeRow(68, 0x007F, 0x0001, 0x2047, 10, 1),
            new SumGrowAeonRecipeRow(69, 0x007F, 0x0002, 0x2046, 1, 1),
            new SumGrowAeonRecipeRow(70, 0x007F, 0x0003, 0x2046, 1, 1),
            new SumGrowAeonRecipeRow(71, 0x007F, 0x0004, 0x2047, 1, 1),
            new SumGrowAeonRecipeRow(72, 0x007F, 0x0005, 0x2047, 1, 1),
            new SumGrowAeonRecipeRow(73, 0x007F, 0x0006, 0x2048, 1, 1),
            new SumGrowAeonRecipeRow(74, 0x007F, 0x0007, 0x204A, 1, 1),
            new SumGrowAeonRecipeRow(75, 0x007F, 0x0008, 0x2048, 1, 1),
            new SumGrowAeonRecipeRow(76, 0x007F, 0x0009, 0x2048, 1, 1),
        };
    }
}
